### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fturco** [larsXYZ/Gravity-Simulator#1]
I'm happy you released source code for this program, but unfortunately that is not enough for qualifying as open-source or free-software. You should also pick a license. Let me suggest you [this](http://choosealicense.com/) website if you don't know which is the best one.

**Comment by larsXYZ** [comment]
I can just copy the one I want into the solution? Is it that easy?

**Comment by fturco** [comment]
Usually free software projects have a `LICENSE` or `COPYING` file in the root directory containing the text of the chosen license. You may also include a license notice at the beginning of each source file (as a comment). Please see [this](http://producingoss.com/en/license-quickstart.html) for details.

**Comment by larsXYZ** [comment]
Okay! Thanks a lot =)

**Comment by qsantos** [comment]
Don't forget to mark the issue as closed ;-) .
