### ISSUE TITLE
finnPlanet not found

### ISSUE THREAD

**Issue by JonnyPtn** [larsXYZ/Gravity-Simulator#13]
Presume it's a typo? Have addressed it here:

https://github.com/JonnyPtn/Gravity-Simulator/commit/93a3dd840e8097dfba81f84a6a43b5caceac4361

**Comment by qsantos** [comment]
[It's Norwegian.](https://translate.google.com/#no/en/finn) Some of the code still need to be translated to English.

**Comment by JonnyPtn** [comment]
Want a PR for it? won't build otherwise

**Comment by JonnyPtn** [comment]
Fixed by https://github.com/larsXYZ/Gravity-Simulator/pull/14
